### ISSUE TITLE
Meteor support

### ISSUE THREAD

**Issue by queso** [yagoferrer/map-tools#198]
Hey,

I saw your presentation at Devshop a few days ago and I liked what I saw. I was curious if you were already using the library in a Meteor app?

You mentioned that you planned to make a Meteor package. Did you plan to make it a way to reactively handle map markers, etc?

**Comment by yagoferrer** [comment]
Hi @queso,
I'm glad you liked!! I'll be creating a new Meteor specific project that will include this Node package as a dependency. I created a repo for this: https://github.com/yagoferrer/meteor-map-tools stay tuned!
