### ISSUE TITLE
Support for neighbourhood overlays. 

### ISSUE THREAD

**Issue by pjakobsen** [yagoferrer/map-tools#283]
As you can see with the following URL, a neighbourhood "place" renders a pink shape file with a red boundary, and includes the neighbourhood name in red letters in the centre.   

    https://www.google.ca/maps/place/Sandy+Hill,+Ottawa,+ON

It's cooked into Google Maps, but I'm not sure if this feature is available in the Google Maps API, so perhaps it's not fair to post a feature request here(?).

**Comment by yagoferrer** [comment]
Yes, this is a Google Maps Site feature. But you can accomplish something similar using Topojoson shapes. Take a look: http://map-tools.io/examples/geojson.html

**Comment by pjakobsen** [comment]
Thank you!

**Comment by pjakobsen** [comment]
@yagoferrer  Hmm, I'm getting a 404 on http://map-tools.io/dist/map-tools.js when accessing your example at http://map-tools.io/examples/geojson.html

**Comment by yagoferrer** [comment]
Problem fixed! Thanks for the heads up.
