### ISSUE TITLE
Non-minified version for debugging?

### ISSUE THREAD

**Issue by pjakobsen** [yagoferrer/map-tools#285]
Are you planning to provide a non-minified version of map-tools?  It should make it easier to debug.

**Comment by yagoferrer** [comment]
@pjakobsen You should be able to download the non-minified version from here:
https://github.com/yagoferrer/map-tools/tree/2.0.0/dist

**Comment by pjakobsen** [comment]
Ah, I see what the trouble was.  I ran "make clean" ,which removed dist/map-tools.js but not dist/map-tools.min.js     

Hence the confusion.   

By the way, when I then try to run "make" I get 

    make: *** No rule to make target `help'.  Stop.

**Comment by yagoferrer** [comment]
Ok I'll have to check what is going on with this but in the midtime 
if you do: `npm run test` it will generate the libraries again for you.
