### ISSUE TITLE
Question: How can I alter GeoJson data before it is placed on the map?

### ISSUE THREAD

**Issue by pjakobsen** [yagoferrer/map-tools#286]
I'd like to add some info windows to incoming geojson data before it's placed on the map. 

     var path = '/earthquakes/feed/v1.0/summary/all_day.geojson';
	$.getJSON(domain + path, function (data) {
          // Do something here to each element, or to some elements
	     map.addGeoJson(data);
	});

**Comment by yagoferrer** [comment]
Hey @pjakobsen,
 since these are Features not Markers, to display an info window you have to attach an event listener to the data object. 
Here it is an example:
```javascript
var map = new mapTools({
    id: 'mymap',
    lat: 35,
    lng: -105,
    zoom: 4
  }, function (err, map) {  
   var infoWindow = new google.maps.InfoWindow({content: ''});  
    if (!err) {
      var domain = 'http://earthquake.usgs.gov';
      var path = '/earthquakes/feed/v1.0/summary/all_day.geojson';
    $.getJSON(domain + path, function (data) {               
        map.addGeoJson(data);      
        map.instance.data.addListener('click', function(event) {          
          var feature = event.feature;          
          infoWindow.setContent('<div>' + feature.data.type + ' Magnitude: ' +feature.data.mag +'</div>');         
          var anchor = new google.maps.MVCObject();
				  anchor.set("position",event.latLng);
				  infoWindow.open(map.instance,anchor);          
        });                
      });    
    }
  });
```

**Comment by yagoferrer** [comment]
I could provide a helper similar to what I have for Markers. Do you have some ideas on how the API should look like @hergert ?

**Comment by pjakobsen** [comment]
@yagoferrer Thank you, this works great so far.  I'll work with it a bit more tomorrow afternoon, and let you know how it goes.

**Comment by pjakobsen** [comment]
I wonder what the best way is to manipulate the position of the InfoWindow, given that the CSS is not accessible by class.  

This seems like a bit of hack for moving the window up above the marker so it doesn't cover it:

          var anchor = new google.maps.MVCObject();
          newLatLng = new google.maps.LatLng(event.latLng.lat()+0.003,event.latLng.lng());
          anchor.set("position",newLatLng);
          infoWindow.open(map.instance,anchor);

Any suggestions?

**Comment by pjakobsen** [comment]
@yagoferrer Forgot to mention that your proposal above makes perfect sense.   I'm sure you are busy, so I'll try to implement it in my fork for your review.   :)

**Comment by yagoferrer** [comment]
@pjakobsen that would be awesome. There is already an implementation for infoWindow:
https://github.com/yagoferrer/map-tools/blob/master/lib/infoWindow.ts
Basically this file needs to be updated so that allows you to attach events to Markers or to map.instance.data directly. Let me know if I can help with that.

**Comment by yagoferrer** [comment]
```javascript
event.latLng.lat()+0.003
```
You could manipulate the CSS for the infoWindow frame: the div found two levels above the .gm-style-iw 
This is another great topic. We could add setting that helps to style infoWindow
